"""Explanation Service.

Generates deterministic, traceable natural-language explanations for
Commander recommendations. Every sentence is tied to a specific COP
observation so explanations are fully auditable.

Design principle: explanations are assembled from evidence fragments,
not generated by an LLM. This makes them reproducible and testable.
Future upgrade path: pass fragments to an LLM for richer prose.
"""
from services.cop_manager import CommonOperatingPicture
from services.priority_engine import PriorityResult


def build_explanation(
    location: str,
    priority: PriorityResult,
    recommended_resource: str | None,
    cop: CommonOperatingPicture,
) -> str:
    """
    Build a human-readable explanation for a rescue recommendation.

    Args:
        location:             Target rescue zone.
        priority:             Scored PriorityResult for this location.
        recommended_resource: Resource ID being dispatched (or None).
        cop:                  Current Common Operating Picture.

    Returns:
        Plain-English explanation string.
    """
    fragments: list[str] = []

    # 1. Incident evidence
    incidents = [i for i in cop.incidents if i.location == location]
    for inc in incidents:
        if inc.severity_label in ("Critical", "High"):
            fac = f" at {inc.facility}" if inc.facility else ""
            ppl = f" affecting {inc.people_count} people" if inc.people_count else ""
            fragments.append(
                f"a {inc.severity_label.lower()} {inc.incident_type} incident{fac}{ppl} is active"
            )

    # 2. Road closure evidence
    closures = [c for c in cop.road_closures if c.location == location]
    for c in closures:
        fragments.append(f"{c.road_name} is blocked, cutting off road access")

    # 3. Route status evidence
    blocked_routes = [r for r in cop.routes if r.destination == location and r.status == "Blocked"]
    rerouted_routes = [r for r in cop.routes if r.destination == location and r.status == "Rerouted"]
    if blocked_routes:
        fragments.append("all primary routes to this zone are currently blocked")
    elif rerouted_routes:
        max_delay = max(r.delay_minutes for r in rerouted_routes)
        fragments.append(f"routes have been rerouted adding up to {max_delay:.0f} minutes of delay")

    # 4. Weather evidence
    if cop.weather.alert_level in ("Orange", "Red"):
        fragments.append(
            f"a {cop.weather.alert_level} weather alert is active "
            f"({cop.weather.condition}, {cop.weather.rainfall_mm_hr:.0f}mm/hr rainfall)"
        )

    # 5. Flood evidence
    if cop.flood.detected and cop.flood.risk_level in ("High", "Critical"):
        fragments.append(
            f"flood coverage is at {cop.flood.coverage_percent}% "
            f"with {cop.flood.water_depth} water depth"
        )

    # 6. Resource dispatch
    if recommended_resource:
        fragments.append(f"{recommended_resource} is the nearest available asset")

    # Assemble
    if not fragments:
        return f"Location {location} has been flagged by the priority engine (score: {priority.score:.0f})."

    body = "; ".join(fragments[:4])   # cap at 4 fragments for readability
    resource_clause = (
        f" {recommended_resource} is recommended for immediate dispatch."
        if recommended_resource else ""
    )
    return f"{body.capitalize()}.{resource_clause}"


def build_factor_explanation(priority: PriorityResult) -> list[str]:
    """Return one sentence per non-zero scoring factor for the UI breakdown panel."""
    lines = []
    f = priority.factors
    w = f.weights

    if f.severity > 0:
        lines.append(f"Severity: {f.severity:.0f}/100 (weight {w['severity']:.0%})")
    if f.population > 0:
        lines.append(f"Population risk: {f.population:.0f}/100 (weight {w['population']:.0%})")
    if f.accessibility > 0:
        lines.append(f"Accessibility loss: {f.accessibility:.0f}/100 (weight {w['accessibility']:.0%})")
    if f.weather > 0:
        lines.append(f"Weather severity: {f.weather:.0f}/100 (weight {w['weather']:.0%})")
    if f.resource > 0:
        lines.append(f"Resource scarcity: {f.resource:.0f}/100 (weight {w['resource']:.0%})")
    return lines
